### PR TITLE
Add second notification point on rip complete

### PR DESCRIPTION
**Pull request by TheNuttyP**
Added a call to the notification script to run on rip completion so that the user is notified both when the rip AND the transcoding is completed.

### CODE REVIEW

**Comment by ahnooie** [comment]
I agree with making this notification an option in the config.  I think the two use cases are a user wants to know when the rip is complete so they can insert the next disc (this PR) or a user wants to know when transcoding is done so they can watch the movie.

**Comment by audioeng** [comment]
Should be a simple if check, I’ll look at putting together a PR for this, I
might have time tomorrow.

I agree with those two use cases, those are the two I like to have at
least. :)

**Comment by audioeng** [comment]
Just submitted #88 PR to make these notifications configurable in the config file. Also added a rip notification to data_rip.sh for consistency.

Only notification that is not around for ripping is the audio rip, as it is not in a separate script. It could be added, but thought some discussion might be warranted for that as a separate PR.

**Comment by ahnooie** [comment]
Thanks!  Closing in favor of #88.

**Pull request closed without merging**
