### PR TITLE
added email notification options

### PR DESCRIPTION
**Pull request by JSylvia007**
Ben,

I think I'm a quick student... First go with Git...  I Forked your repo over to my Git, created a branch, made the changes to notify.sh and config.sample.  I tested these out on my system, and they work.

Hopefully this get over to you for incorporation.

### CODE REVIEW

**Comment by audioeng** [comment]
I like the idea, but I am curious as to the need for mutt. Seems like this could be done with only postfix.

**Comment by JSylvia007** [comment]
Not sure how you could do this with just postfix as postfix is only the mail server.  It has no way to send mail itself, it's merely the transport service.  

I've toyed around with a bunch of different command line mailers, and mutt seems to handle everything I've thrown at it, including complex HTML/XML and attachments.

**Comment by audioeng** [comment]
Here is a good example of configuring postfix to [send an email from a gmail account.](https://easyengine.io/tutorials/linux/ubuntu-postfix-gmail-smtp/)

**Comment by JSylvia007** [comment]
Right...  Notice that the command for testing echo's something to "mail"?  You still need a client. I prefer mutt over mail, that's all.

**Comment by audioeng** [comment]
Ahh, but mail is already there, so you don't have to install and configure
something else. If you are sending via a command line script, whether you
like the mail client better is irrelevant, you don't see it. Ease of
configuration should be primary I think.

**Comment by JSylvia007** [comment]
Technically, mail is added as part of mailutils, also referenced in that guide.  As I mentioned previously, mutt handles richly formatted emails and attachments, as well as more complex workflows far more elegantly than mail does.  Additionally, no configration is required, it's just simply `apt-get install mutt`

**Comment by JSylvia007** [comment]
Awesome... I think you'll like mutt for flexibility.  The reason that I use postfix is because I have multiple things setup in a 10's of servers environment and it just makes it easier.

I just made and pushed those changes.

**Comment by ahnooie** [comment]
Can you add a link to a mutt guide (the one @audioeng linked to is fine) in the config.sample file so people who use this option will know how to configure mutt?  Once that's done it looks good to me.

**Comment by JSylvia007** [comment]
Language added!

**Comment by JSylvia007** [comment]
Thanks @ahnooie !!

I've loved contributing to this project!!

**Pull request merged**
