### PR TITLE
python dvd ripping

### PR DESCRIPTION
**Pull request by muckngrind4**
Moved all dvd processing from batch to python.

### CODE REVIEW

**Comment by ahnooie** [comment]
Getting close.  For me it's failing with:

`    "could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "/opt/arm/arm/config.yaml", line 30, column 1
could not find expected ':'
  in "/opt/arm/arm/config.yaml", line 31, column 16`

Looking at line 30 and 31 in my config.yaml that was generated... I'm guessing that it shouldn't have brought over the bash if else statement...
```
29 - IFTTT_EVENT: "arm_event"
30 - if [ -z "$ID_FS_LABEL" ]; then
31 -         LOGFILE: "empty.log"
32 - else
33 -         LOGFILE: ${ID_FS_LABEL}".log"
34 - fi
35 - LOG: $LOGPATH$LOGFILE
```
What's the best way to fix this?  Did you have to take that if statement out of your config file?

Here's my config file:

```
# ARM (Automatic Ripping Machine) oonfig file

#################
## ARM Options ##
#################

# Distinguish UDF video discs from UDF data discs.  Requires mounting disc so a
dds a few seconds to the identify script.
ARM_CHECK_UDF=true

# When enabled if the disc is a DVD use dvdid to calculate a crc64 and query Wi
ndows Media Meta Services for the Movie Title.
# For BluRays attempts to extract the title from an XML file on the disc
GET_VIDEO_TITLE=true

#####################
## Directory setup ##
#####################

# Base directory of ARM media directory
# Ripped and transcoded files end up here
ARMPATH="/mnt/media/ARMTEST/"

# Path to raw MakeMKV directory
# Destination for MakeMKV and source for HandBrake
RAWPATH="/mnt/media/ARMTEST/raw/"

# Path to final media directory
# Destination for final file.  Only used for movies that are positively identif
ied
MEDIA_DIR="/mnt/media/ARMTEST/emby/movies/"

# Path to directory to hold log files
# Make sure to include trailing /
LOGPATH="/opt/arm/logs/"

# How long to let log files live before deleting (in days)
LOGLIFE=1


#####################
## Enable Plex Use ##
#####################

# Set this setting to true, to enable Plex Extras support
PLEX_SUPPORT=false


########################
## MakeMKV Parameters ##
########################

# Minimum length of track for MakeMKV rip (in seconds)
MINLENGTH="60"

# Method of MakeMKV to use for Blu Ray discs.  Options are "mkv" or "backup".
# mkv is the normal method of ripping mkv files directly from the DVD
# backup decrypts the dvd and then copies it to the hard drive.  This allows Ha
ndBrake to apply some of it's
# analytical abilities such as the main-feature identification.  This method se
ems to offer success on bluray 
# discs that fail in "mkv" mode. *** NOTE: MakeMKV only supports the backup met
hod on BluRay discs.  Regular
# DVD's will always default back to the "mkv" mode. If this is set to "backup" 
then you must also set HandBrake's MAINFEATURE to true. 
RIPMETHOD="backup" 

########################
##  File Permissions  ##
########################

# Enabling this seting will allow you to adjust the default file permissions of
 the outputted files
# The default value is set to 777 for read/write/execute for all users, but can
 be changed below using the "CHMOD_VALUE" setting
# This setting is helpfuly when storing the data locally on the system
SET_MEDIA_PERMISSIONS=false
CHMOD_VALUE=777


##########################
## HandBrake Parameters ##
##########################

# Handbrake preset profile
# Execute "HandBrakeCLI -z" to see a list of all presets
HB_PRESET="High Profile" 
#HB_PRESET="iPod" 

# Extension of the final video file
DEST_EXT=mkv

# Handbrake binary to call
HANDBRAKE_CLI=HandBrakeCLI

# Have HandBrake transcode the main feature only.  BluRay discs must have RIPME
THOD="backup" for this to work.
# If MAINFEATURE is true, blurays will be backed up to the HD and then HandBrak
e will go to work on the backed up
# files.  For normal DVDs, ARM will bypass MakeMKV and hand off the dvd directl
y to HandBrake.  This will require 
# libdvdcss2 be installed.
# NOTE: For the most part, HandBrake correctly identifies the main feature on m
ovie DVD's, although it is not perfect. 
# However, it does not handle tv shows well at all.  You will likely want this 
value to be false when ripping tv shows.
MAINFEATURE=false

#HB_ARGS="--native-language eng --subtitle scan,1,2,3,4,5,6,7,8,9,10 --subtitle
-default=1 --audio-lang-list eng --all-audio"
#HB_ARGS="--subtitle scan -F --subtitle-lang-list eng --all-subtitles"
HB_ARGS="--native-language eng --subtitle scan,1,2,3,4,5,6,7,8,9,10 --subtitle-
default=1 --subtitle-forced=1 --audio-lang-list eng --all-audio"

#####################
## Emby Parameters ##
#####################

# Parameters to enable automatic library scan in Emby.  This will trigger only 
if MainFeature is true above.

# Scan emby library after succesful placement of mainfeature (see above)
EMBY_REFRESH=true

# Server parameters
# Server can be ip address or domain name
EMBY_SERVER="removed"
EMBY_PORT="8096"

# Emby authentication fluff parameters.  These can be anything.
EMBY_CLIENT="ARM"
EMBY_DEVICE="ARM"
EMBY_DEVICEID="ARM"

# Emby authentication parameters.  These are parameters that must be set to a c
urrent user in Emby.
EMBY_USERNAME="removed"

# EMBY_USERID is the user ID associated with the username above.  You can find 
this by going to the following address on your emby server
# <server>:<port>/Users/Public and getting the ID value for the username above.
EMBY_USERID="removed"

# This is the SHA1 encrypted password for the username above.  You can generate
 the SHA1 hash of your password by executing the following at
# the command line: 
# echo -n your-password | sha1sum | awk '{print $1}'
# or using an online generator like the one located at http://www.sha1-online.c
om/
EMBY_PASSWORD="removed"


# MakeMKV Arguments
# MakeMKV Profile used for controlling Audio Track Selection.
# This is the default profile MakeMKV uses for Audio track selection. Updating 
this file or changing it is considered
# to be advanced usage of MakeMKV. But this will allow users to alternatively t
ell makemkv to select HD audio tracks and etc.
# MKV_ARGS="--profile=/opt/arm/default.mmcp.xml"
MKV_ARGS=""



#############################
## Notification Parameters ##
#############################

# Pushbullet API Key
# Leave empty or comment out to disable Pushbullet notifications
PB_KEY=""

# IFTTT API KEY
# Leave empty or comment out to disable IFTTT notifications
# IFTTT_KEY=""

# IFTTT Event Name
IFTTT_EVENT="arm_event"

# Determine logfile name
# use the label of the DVD/CD or else use empty.log
# this is required for udev events where there is no media available
# such as ejecting the drive
if [ -z "$ID_FS_LABEL" ]; then
        LOGFILE="empty.log"
else
        LOGFILE=${ID_FS_LABEL}".log"
fi

# Set full logfile path
LOG=$LOGPATH$LOGFILE


```

**Comment by muckngrind4** [comment]
I forgot to add the stop line to the config.sample file.  It's now added.

**Comment by ahnooie** [comment]
Starting tests.  Just keeping notes on requirements: So far had to install python packages: yaml, pyyaml (not sure if both are needed, but yaml definitely was) and lsdvd from apt.

**Comment by ahnooie** [comment]
@muckngrind4  So one problem (which I found a workaround for already) is the bash to python vars was changing the = to : 

My config has: 

```HB_ARGS="--native-language eng --subtitle scan,1,2,3,4,5,6,7,8,9,10 --subtitle-default=1 --subtitle-forced=1 --audio-lang-list eng --all-audio"```

And this get's converted to the below (notice the "=" gets converted to a ":" on `--subtitle-default: 1` 

```HB_ARGS: "--native-language eng --subtitle scan,1,2,3,4,5,6,7,8,9,10 --subtitle-default: 1 --subtitle-forced: 1 --audio-lang-list eng --all-audio"```

Which of course isn't valid for HandBrake...  

```
[21:43:47] thread 7fe3751b2700 started ("libhb")
unknown option (--subtitle-default:)
[2017-07-30 21:43:47] ARM: ERROR Call to handbrake failed with code: 1(b'')
```
I got around it be setting `subtitle-forced 1` and that should work, but something to keep in mind that we may run into issues if = is part of the args when calling CLI programs from python.

**Comment by ahnooie** [comment]
Foiled... 
Scanning title 1 of 1, preview 1, 10.00 %ERROR: dvdnav: Read Error, Error reading NAV packet.
[21:51:06] Warning: Could not read data for preview 1, skipped
[21:51:06] scan: decoding previews for title 1
libdvdnav: DVD disk reports itself with Region mask 0x00fe0000. Regions: 1
[21:51:06] scan: title angle(s) 1
[21:51:06] Warning: Could not read data for preview 1, skipped
[21:51:06] libhb: scan thread found 0 valid title(s)
No title found.
HandBrake has exited.
[2017-07-30 21:51:06] ARM: ERROR Call to handbrake failed with code: 2(b'')
[2017-07-30 21:51:06] ARM: INFO DVD processing comlete

**Comment by muckngrind4** [comment]
I probably need to configure the parser to ignore anything after the " or maybe after the first =. I'll take a look at it.

**Comment by muckngrind4** [comment]
I've committed a change to limit the = sub to one instance....

**Comment by muckngrind4** [comment]
Added pushbullet and ifttt notifications.  Two new requirements pushbullet.py and pyfttt.  Both have been added to requirements.txt

**Pull request closed without merging**
