### PR TITLE
Dep omdbapi key, Fixes root cause of issue #57.

### PR DESCRIPTION
**Pull request by cbunt1**
We have a fix for the root cause of Issue #57 . At this point I have purchased a year-long API key which I'm willing to share for testing (contact me directly). The fix follows the format of the other API keys and such by storing the key in the config file. Note that the PR version has been sanitized of the API key.

### CODE REVIEW

**Comment by jswetzen** [comment]
I'd like to test this, will email you about the key.

**Comment by cbunt1** [comment]
Sorry for my delayed response. The key is in the email, so to speak. :)

**Comment by jswetzen** [comment]
I can confirm that it's working, and the code looks good to me as well.

**Comment by cbunt1** [comment]
I think that should do it. Let me know if I removed files that we should have kept.

**Comment by ahnooie** [comment]
Looks good to me, thanks for adding this!

**Comment by jswetzen** [comment]
You lost requirements.txt, one text file too many.

**Comment by cbunt1** [comment]
OOPS! 

I also pulled the README-OMDBAPI file. Let me know if I should re-add it, since it has the docs for using the api key.

**Comment by ahnooie** [comment]
Oops, I missed the requirements as well.  I think it's a good idea to add the omdbapi readme back as well.

**Comment by cbunt1** [comment]
I re-added requirements.txt and omdbapi-readme. They came up as a separate pull request, but I think I have everything fixed now.

**Pull request merged**
